### ISSUE TITLE
Create standard Verify and Release workflows

### ISSUE THREAD

**Issue by EricWittmann** [Apicurio/apicurio-common-app-components#11]
We should be able to just do something similar to what we already have in `apicurio-common-rest-client` for this.

**Comment by riprasad** [comment]
@EricWittmann Looks like both the workflows are already in place and working. Were you looking for some custom modifications instead?

**Comment by EricWittmann** [comment]
Geez!  I didn't even remember doing that.  Sorry for the noise @riprasad
